# This is a basic workflow to help you get started with Actions

name: Rule_Generate
on:
  push:
    branches:
      - master
  schedule:
    - cron: '0 20 * * *'
  
# Controls when the workflow will run
  # Triggers the workflow on push or pull request events but only for the "main" branch
  pull_request:
    branches: [ "main" ]
  
  repository_dispatch:
    types: [bot_trigger]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      # Runs a single command using the runners shell
      - name: "拉取"
        #run: for f in Script/*.py; do python "$f"; done
        run: python Script/Get_File.py
      - name: "合并"
        run: python Script/Merge_File.py
      - name: Commit files
        run: |
          git config --local user.email "lu982524190@gmail.com"
          git config --local user.name "Code-Dramatist"
          git add ./*
          git commit -m "Update Rules" -a
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ github.ref }}
